GIT_URL: git@gitlab.moduldev.ru:abs/plplus.git
WORKING_GIT_FOLDER: C:\Users\ivan\Documents\prj\py\plplus
ORACLE_HOME: C:\app\ivan\product\11.2.0\client_1
USERS_TO_SAVE_OBJECTS_IN_GIT: ['BryzzhinIS', 'DoblerEA', 'smirnovan', 'usovvs', 'SysovaEA', 'UrypinaAV', 'kashapovar',
                               'matveevsa', 'pichuginain', 'shavkunov', 'tihonoviv', 'Tyrykina', 'Morozovasi', ]

TNS:
  ass: ibs/HtuRhtl@lw-ass-abs
  abs: ibs/HtuRhtl@lw-abs-abs
  p2: ibs/HtuRhtl@lw-p2-abs
  msb: ibs/HtuRhtl@msb
  mid: ibs/HtuRhtl@midabs
  day: ibs/HtuRhtl@day
  midday: ibs/HtuRhtl@MIDEVERYDAY
  ssd: ibs/HtuRhtl@mid-abs-ssd
  p2@p2: portal2/HtuRhtl@lw-p2-abs
DEFAULT_TNS: p2

pandas:
  display.width: 500
  display.max_rows:
  display.max_columns:


# настройки логгирования
LOGGING:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    full:
      format: '%(asctime)s [%(name)s:%(lineno)s] [%(levelname)s] [%(processName)s,%(threadName)s] %(funcName)s - %(message)s'

  handlers:
    error_console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: full
      stream: ext://sys.stderr # еще может быть ext://sys.stdout

    debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: info.log
      encoding: utf8
      delay: True

    error_file_handler:
      class:    logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: full
      # если указать относительный путь, то путь считается от корня проекта
      filename: errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  loggers:
    database_client.oracle:
      level: INFO
      handlers: [error_console]
      propagate: no
    git:
      level: INFO

  root:
    level: DEBUG
    handlers: [error_console, error_file_handler]